ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [GiveCRM.Admin.Database], FILENAME = 'D:\SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\GiveCRM.Admin.Database.mdf', SIZE = 2304 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

